'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.288
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsHRrpt
    Inherits DataSet
    
    Private tableCrystalReportsHRData As CrystalReportsHRDataDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("CrystalReportsHRData")) Is Nothing) Then
                Me.Tables.Add(New CrystalReportsHRDataDataTable(ds.Tables("CrystalReportsHRData")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property CrystalReportsHRData As CrystalReportsHRDataDataTable
        Get
            Return Me.tableCrystalReportsHRData
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsHRrpt = CType(MyBase.Clone,dsHRrpt)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("CrystalReportsHRData")) Is Nothing) Then
            Me.Tables.Add(New CrystalReportsHRDataDataTable(ds.Tables("CrystalReportsHRData")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableCrystalReportsHRData = CType(Me.Tables("CrystalReportsHRData"),CrystalReportsHRDataDataTable)
        If (Not (Me.tableCrystalReportsHRData) Is Nothing) Then
            Me.tableCrystalReportsHRData.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsHRrpt"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsHRrpt.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableCrystalReportsHRData = New CrystalReportsHRDataDataTable
        Me.Tables.Add(Me.tableCrystalReportsHRData)
    End Sub
    
    Private Function ShouldSerializeCrystalReportsHRData() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub CrystalReportsHRDataRowChangeEventHandler(ByVal sender As Object, ByVal e As CrystalReportsHRDataRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class CrystalReportsHRDataDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnHR As DataColumn
        
        Private columnHRDataKey As DataColumn
        
        Private columnSampleTime As DataColumn
        
        Friend Sub New()
            MyBase.New("CrystalReportsHRData")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property HRColumn As DataColumn
            Get
                Return Me.columnHR
            End Get
        End Property
        
        Friend ReadOnly Property HRDataKeyColumn As DataColumn
            Get
                Return Me.columnHRDataKey
            End Get
        End Property
        
        Friend ReadOnly Property SampleTimeColumn As DataColumn
            Get
                Return Me.columnSampleTime
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As CrystalReportsHRDataRow
            Get
                Return CType(Me.Rows(index),CrystalReportsHRDataRow)
            End Get
        End Property
        
        Public Event CrystalReportsHRDataRowChanged As CrystalReportsHRDataRowChangeEventHandler
        
        Public Event CrystalReportsHRDataRowChanging As CrystalReportsHRDataRowChangeEventHandler
        
        Public Event CrystalReportsHRDataRowDeleted As CrystalReportsHRDataRowChangeEventHandler
        
        Public Event CrystalReportsHRDataRowDeleting As CrystalReportsHRDataRowChangeEventHandler
        
        Public Overloads Sub AddCrystalReportsHRDataRow(ByVal row As CrystalReportsHRDataRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddCrystalReportsHRDataRow(ByVal HR As Integer, ByVal SampleTime As Date) As CrystalReportsHRDataRow
            Dim rowCrystalReportsHRDataRow As CrystalReportsHRDataRow = CType(Me.NewRow,CrystalReportsHRDataRow)
            rowCrystalReportsHRDataRow.ItemArray = New Object() {HR, Nothing, SampleTime}
            Me.Rows.Add(rowCrystalReportsHRDataRow)
            Return rowCrystalReportsHRDataRow
        End Function
        
        Public Function FindByHRDataKey(ByVal HRDataKey As Integer) As CrystalReportsHRDataRow
            Return CType(Me.Rows.Find(New Object() {HRDataKey}),CrystalReportsHRDataRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As CrystalReportsHRDataDataTable = CType(MyBase.Clone,CrystalReportsHRDataDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New CrystalReportsHRDataDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnHR = Me.Columns("HR")
            Me.columnHRDataKey = Me.Columns("HRDataKey")
            Me.columnSampleTime = Me.Columns("SampleTime")
        End Sub
        
        Private Sub InitClass()
            Me.columnHR = New DataColumn("HR", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnHR)
            Me.columnHRDataKey = New DataColumn("HRDataKey", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnHRDataKey)
            Me.columnSampleTime = New DataColumn("SampleTime", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSampleTime)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnHRDataKey}, true))
            Me.columnHRDataKey.AutoIncrement = true
            Me.columnHRDataKey.AllowDBNull = false
            Me.columnHRDataKey.Unique = true
        End Sub
        
        Public Function NewCrystalReportsHRDataRow() As CrystalReportsHRDataRow
            Return CType(Me.NewRow,CrystalReportsHRDataRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New CrystalReportsHRDataRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(CrystalReportsHRDataRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.CrystalReportsHRDataRowChangedEvent) Is Nothing) Then
                RaiseEvent CrystalReportsHRDataRowChanged(Me, New CrystalReportsHRDataRowChangeEvent(CType(e.Row,CrystalReportsHRDataRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.CrystalReportsHRDataRowChangingEvent) Is Nothing) Then
                RaiseEvent CrystalReportsHRDataRowChanging(Me, New CrystalReportsHRDataRowChangeEvent(CType(e.Row,CrystalReportsHRDataRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.CrystalReportsHRDataRowDeletedEvent) Is Nothing) Then
                RaiseEvent CrystalReportsHRDataRowDeleted(Me, New CrystalReportsHRDataRowChangeEvent(CType(e.Row,CrystalReportsHRDataRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.CrystalReportsHRDataRowDeletingEvent) Is Nothing) Then
                RaiseEvent CrystalReportsHRDataRowDeleting(Me, New CrystalReportsHRDataRowChangeEvent(CType(e.Row,CrystalReportsHRDataRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveCrystalReportsHRDataRow(ByVal row As CrystalReportsHRDataRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class CrystalReportsHRDataRow
        Inherits DataRow
        
        Private tableCrystalReportsHRData As CrystalReportsHRDataDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableCrystalReportsHRData = CType(Me.Table,CrystalReportsHRDataDataTable)
        End Sub
        
        Public Property HR As Integer
            Get
                Try 
                    Return CType(Me(Me.tableCrystalReportsHRData.HRColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableCrystalReportsHRData.HRColumn) = value
            End Set
        End Property
        
        Public Property HRDataKey As Integer
            Get
                Return CType(Me(Me.tableCrystalReportsHRData.HRDataKeyColumn),Integer)
            End Get
            Set
                Me(Me.tableCrystalReportsHRData.HRDataKeyColumn) = value
            End Set
        End Property
        
        Public Property SampleTime As Date
            Get
                Try 
                    Return CType(Me(Me.tableCrystalReportsHRData.SampleTimeColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableCrystalReportsHRData.SampleTimeColumn) = value
            End Set
        End Property
        
        Public Function IsHRNull() As Boolean
            Return Me.IsNull(Me.tableCrystalReportsHRData.HRColumn)
        End Function
        
        Public Sub SetHRNull()
            Me(Me.tableCrystalReportsHRData.HRColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSampleTimeNull() As Boolean
            Return Me.IsNull(Me.tableCrystalReportsHRData.SampleTimeColumn)
        End Function
        
        Public Sub SetSampleTimeNull()
            Me(Me.tableCrystalReportsHRData.SampleTimeColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class CrystalReportsHRDataRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As CrystalReportsHRDataRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As CrystalReportsHRDataRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As CrystalReportsHRDataRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
