'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.0.3705.288
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsSpO2rpt
    Inherits DataSet
    
    Private tableCrystalReportsSpO2Data As CrystalReportsSpO2DataDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("CrystalReportsSpO2Data")) Is Nothing) Then
                Me.Tables.Add(New CrystalReportsSpO2DataDataTable(ds.Tables("CrystalReportsSpO2Data")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property CrystalReportsSpO2Data As CrystalReportsSpO2DataDataTable
        Get
            Return Me.tableCrystalReportsSpO2Data
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsSpO2rpt = CType(MyBase.Clone,dsSpO2rpt)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("CrystalReportsSpO2Data")) Is Nothing) Then
            Me.Tables.Add(New CrystalReportsSpO2DataDataTable(ds.Tables("CrystalReportsSpO2Data")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableCrystalReportsSpO2Data = CType(Me.Tables("CrystalReportsSpO2Data"),CrystalReportsSpO2DataDataTable)
        If (Not (Me.tableCrystalReportsSpO2Data) Is Nothing) Then
            Me.tableCrystalReportsSpO2Data.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsSpO2rpt"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsSpO2rpt.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableCrystalReportsSpO2Data = New CrystalReportsSpO2DataDataTable
        Me.Tables.Add(Me.tableCrystalReportsSpO2Data)
    End Sub
    
    Private Function ShouldSerializeCrystalReportsSpO2Data() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub CrystalReportsSpO2DataRowChangeEventHandler(ByVal sender As Object, ByVal e As CrystalReportsSpO2DataRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class CrystalReportsSpO2DataDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnSampleTime As DataColumn
        
        Private columnSpO2 As DataColumn
        
        Private columnSpO2DataKey As DataColumn
        
        Friend Sub New()
            MyBase.New("CrystalReportsSpO2Data")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property SampleTimeColumn As DataColumn
            Get
                Return Me.columnSampleTime
            End Get
        End Property
        
        Friend ReadOnly Property SpO2Column As DataColumn
            Get
                Return Me.columnSpO2
            End Get
        End Property
        
        Friend ReadOnly Property SpO2DataKeyColumn As DataColumn
            Get
                Return Me.columnSpO2DataKey
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As CrystalReportsSpO2DataRow
            Get
                Return CType(Me.Rows(index),CrystalReportsSpO2DataRow)
            End Get
        End Property
        
        Public Event CrystalReportsSpO2DataRowChanged As CrystalReportsSpO2DataRowChangeEventHandler
        
        Public Event CrystalReportsSpO2DataRowChanging As CrystalReportsSpO2DataRowChangeEventHandler
        
        Public Event CrystalReportsSpO2DataRowDeleted As CrystalReportsSpO2DataRowChangeEventHandler
        
        Public Event CrystalReportsSpO2DataRowDeleting As CrystalReportsSpO2DataRowChangeEventHandler
        
        Public Overloads Sub AddCrystalReportsSpO2DataRow(ByVal row As CrystalReportsSpO2DataRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddCrystalReportsSpO2DataRow(ByVal SampleTime As Date, ByVal SpO2 As Integer) As CrystalReportsSpO2DataRow
            Dim rowCrystalReportsSpO2DataRow As CrystalReportsSpO2DataRow = CType(Me.NewRow,CrystalReportsSpO2DataRow)
            rowCrystalReportsSpO2DataRow.ItemArray = New Object() {SampleTime, SpO2, Nothing}
            Me.Rows.Add(rowCrystalReportsSpO2DataRow)
            Return rowCrystalReportsSpO2DataRow
        End Function
        
        Public Function FindBySpO2DataKey(ByVal SpO2DataKey As Integer) As CrystalReportsSpO2DataRow
            Return CType(Me.Rows.Find(New Object() {SpO2DataKey}),CrystalReportsSpO2DataRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As CrystalReportsSpO2DataDataTable = CType(MyBase.Clone,CrystalReportsSpO2DataDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New CrystalReportsSpO2DataDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnSampleTime = Me.Columns("SampleTime")
            Me.columnSpO2 = Me.Columns("SpO2")
            Me.columnSpO2DataKey = Me.Columns("SpO2DataKey")
        End Sub
        
        Private Sub InitClass()
            Me.columnSampleTime = New DataColumn("SampleTime", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSampleTime)
            Me.columnSpO2 = New DataColumn("SpO2", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSpO2)
            Me.columnSpO2DataKey = New DataColumn("SpO2DataKey", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnSpO2DataKey)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnSpO2DataKey}, true))
            Me.columnSpO2DataKey.AutoIncrement = true
            Me.columnSpO2DataKey.AllowDBNull = false
            Me.columnSpO2DataKey.Unique = true
        End Sub
        
        Public Function NewCrystalReportsSpO2DataRow() As CrystalReportsSpO2DataRow
            Return CType(Me.NewRow,CrystalReportsSpO2DataRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New CrystalReportsSpO2DataRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(CrystalReportsSpO2DataRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.CrystalReportsSpO2DataRowChangedEvent) Is Nothing) Then
                RaiseEvent CrystalReportsSpO2DataRowChanged(Me, New CrystalReportsSpO2DataRowChangeEvent(CType(e.Row,CrystalReportsSpO2DataRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.CrystalReportsSpO2DataRowChangingEvent) Is Nothing) Then
                RaiseEvent CrystalReportsSpO2DataRowChanging(Me, New CrystalReportsSpO2DataRowChangeEvent(CType(e.Row,CrystalReportsSpO2DataRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.CrystalReportsSpO2DataRowDeletedEvent) Is Nothing) Then
                RaiseEvent CrystalReportsSpO2DataRowDeleted(Me, New CrystalReportsSpO2DataRowChangeEvent(CType(e.Row,CrystalReportsSpO2DataRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.CrystalReportsSpO2DataRowDeletingEvent) Is Nothing) Then
                RaiseEvent CrystalReportsSpO2DataRowDeleting(Me, New CrystalReportsSpO2DataRowChangeEvent(CType(e.Row,CrystalReportsSpO2DataRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveCrystalReportsSpO2DataRow(ByVal row As CrystalReportsSpO2DataRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class CrystalReportsSpO2DataRow
        Inherits DataRow
        
        Private tableCrystalReportsSpO2Data As CrystalReportsSpO2DataDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableCrystalReportsSpO2Data = CType(Me.Table,CrystalReportsSpO2DataDataTable)
        End Sub
        
        Public Property SampleTime As Date
            Get
                Try 
                    Return CType(Me(Me.tableCrystalReportsSpO2Data.SampleTimeColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableCrystalReportsSpO2Data.SampleTimeColumn) = value
            End Set
        End Property
        
        Public Property SpO2 As Integer
            Get
                Try 
                    Return CType(Me(Me.tableCrystalReportsSpO2Data.SpO2Column),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableCrystalReportsSpO2Data.SpO2Column) = value
            End Set
        End Property
        
        Public Property SpO2DataKey As Integer
            Get
                Return CType(Me(Me.tableCrystalReportsSpO2Data.SpO2DataKeyColumn),Integer)
            End Get
            Set
                Me(Me.tableCrystalReportsSpO2Data.SpO2DataKeyColumn) = value
            End Set
        End Property
        
        Public Function IsSampleTimeNull() As Boolean
            Return Me.IsNull(Me.tableCrystalReportsSpO2Data.SampleTimeColumn)
        End Function
        
        Public Sub SetSampleTimeNull()
            Me(Me.tableCrystalReportsSpO2Data.SampleTimeColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsSpO2Null() As Boolean
            Return Me.IsNull(Me.tableCrystalReportsSpO2Data.SpO2Column)
        End Function
        
        Public Sub SetSpO2Null()
            Me(Me.tableCrystalReportsSpO2Data.SpO2Column) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class CrystalReportsSpO2DataRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As CrystalReportsSpO2DataRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As CrystalReportsSpO2DataRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As CrystalReportsSpO2DataRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
